"""Add full PRD schema

Revision ID: d669e0f3d818
Revises: 1479a74e9f6d
Create Date: 2026-08-07 07:25:02.743598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd669e0f3d818'
down_revision: Union[str, Sequence[str], None] = '1479a74e9f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_name', sa.String(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('prevention', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_disease_name'), 'knowledge_base', ['disease_name'], unique=True)
    op.create_index(op.f('ix_knowledge_base_id'), 'knowledge_base', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('crop_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_site_id', sa.Integer(), nullable=True),
    sa.Column('recommended_crop', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farm_site_id'], ['farm_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_recommendations_id'), 'crop_recommendations', ['id'], unique=False)
    op.create_table('disease_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_site_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('detected_disease', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farm_site_id'], ['farm_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_reports_id'), 'disease_reports', ['id'], unique=False)
    op.create_table('season_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_site_id', sa.Integer(), nullable=True),
    sa.Column('crop_planted', sa.String(), nullable=True),
    sa.Column('plant_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('harvest_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('yield_amount_kg', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['farm_site_id'], ['farm_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_logs_id'), 'season_logs', ['id'], unique=False)
    op.create_table('soil_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_site_id', sa.Integer(), nullable=True),
    sa.Column('nitrogen', sa.Float(), nullable=True),
    sa.Column('phosphorus', sa.Float(), nullable=True),
    sa.Column('potassium', sa.Float(), nullable=True),
    sa.Column('ph_level', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farm_site_id'], ['farm_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_readings_id'), 'soil_readings', ['id'], unique=False)
    op.add_column('farm_sites', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'farm_sites', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farm_sites', type_='foreignkey')
    op.drop_column('farm_sites', 'owner_id')
    op.drop_index(op.f('ix_soil_readings_id'), table_name='soil_readings')
    op.drop_table('soil_readings')
    op.drop_index(op.f('ix_season_logs_id'), table_name='season_logs')
    op.drop_table('season_logs')
    op.drop_index(op.f('ix_disease_reports_id'), table_name='disease_reports')
    op.drop_table('disease_reports')
    op.drop_index(op.f('ix_crop_recommendations_id'), table_name='crop_recommendations')
    op.drop_table('crop_recommendations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_knowledge_base_id'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_disease_name'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    # ### end Alembic commands ###
